<?php
/**
 * Provide a public-facing view for the plugin
 *
 * This file is used to markup the public-facing aspects of the plugin.
 *
 * @link       https://racmanuel.dev
 * @since      1.0.0
 *
 * @package    Qr_Link_Generator_For_Wp
 * @subpackage Qr_Link_Generator_For_Wp/public/partials
 */

?>

<!-- Code Generated by QR Link Generator for WP -->
<div class="qr-link-generator-for-wp-row" id="qr-link-generator-for-wp">
    <div class="qr-link-generator-for-wp-column">
        <form id="qr-link-generator-for-wp-form" action="" method="post">
            <input type="text" id="qr-link-generator-for-wp-input-value" value="Insert you content, here.">
        </form>
        <div id="qr-link-generator-for-wp-qr-code"></div>
        <div id="qr-link-generator-for-wp-credits">
            <p>Made with ❤ and Code by <a href="http://racmanuel.dev">racmanuel.</a></p>
        </div>
    </div>
</div>