<?php
/**
 * Provide a public-facing view for the plugin
 *
 * This file is used to markup the public-facing aspects of the plugin.
 *
 * @link       https://racmanuel.dev
 * @since      1.0.0
 *
 * @package    Qr_Link_Generator_For_Wp
 * @subpackage Qr_Link_Generator_For_Wp/public/partials
 */

?>

<!-- Code Generated by QR Link Generator for WP -->

<div class="<?= $this->plugin_name . '-row'; ?>" id="<?=$this->plugin_name;?>">
    <div class="<?= $this->plugin_name . '-column'; ?>">
        <form id="<?=$this->plugin_name . '-form';?>" action="" method="post">
            <input type="text" id="<?=$this->plugin_name . '-input-value'?>" value="Insert you content, here.">
        </form>
        <div id="<?=$this->plugin_name . '-qr-code';?>"></div>
        <div id="<?=$this->plugin_name . '-credits';?>">
            <p>Made with ❤ and WordPress by <a href="http://racmanuel.dev">racmanuel.</a></p>
        </div>
    </div>
</div>