<?php
/**
 * Provide a public-facing view for the plugin
 *
 * This file is used to markup the public-facing aspects of the plugin.
 *
 * @link       https://racmanuel.dev
 * @since      1.0.0
 *
 * @package    Qr_Link_Generator_For_Wp
 * @subpackage Qr_Link_Generator_For_Wp/public/partials
 */
?>

<!-- Code Generated by QR Link Generator for WP -->
<div id="qr-link-generator-for-wp">
    <p style="text-align: <?php echo $align; ?>;">
        <img src="<?php echo $qrcode->render($URL) ?>" alt="QR Code" width="<?php echo $size . 'px'; ?>" />
        <br>
        <a href="<?php echo $qrcode->render($URL); ?>" download="QR_Code.png" class="display: <?php echo $class; ?>">
            <button type="button" class="button"
                style="background-color: <?php echo $button_background_color; ?>; color: <?php echo $button_color ?>;"><?php echo $text_download ?></button>
        </a>
    </p>
</div>